#if !canImport(ObjectiveC)
    import XCTest

    extension ElasticSwiftNetworkingTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ElasticSwiftNetworkingTests = [
            ("test_01_adaptor_init", test_01_adaptor_init),
            ("test_02_adaptor_execute", test_02_adaptor_execute),
            ("test_03_ssl_config", test_03_ssl_config),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(ElasticSwiftNetworkingTests.__allTests__ElasticSwiftNetworkingTests),
        ]
    }
#endif
