#if !canImport(ObjectiveC)
    import XCTest

    extension ElasticSwiftCoreTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__ElasticSwiftCoreTests = [
            ("test_01_httpRequestBuilder", test_01_httpRequestBuilder),
            ("test_02_httpRequestBuilder", test_02_httpRequestBuilder),
            ("test_03_httpRequestBuilder_fail", test_03_httpRequestBuilder_fail),
            ("test_04_httpRequestBuilder_fail_2", test_04_httpRequestBuilder_fail_2),
            ("test_05_httpRequest_queryPath", test_05_httpRequest_queryPath),
            ("test_05_httpRequest", test_05_httpRequest),
            ("test_06_httpResponseBuilder_fail", test_06_httpResponseBuilder_fail),
            ("test_07_httpResponseBuilder_fail_2", test_07_httpResponseBuilder_fail_2),
            ("test_08_httpResponseBuilder_fail_3", test_08_httpResponseBuilder_fail_3),
            ("test_09_httpResponseBuilder", test_09_httpResponseBuilder),
            ("test_10_HTTPResponseStatus_extension_test", test_10_HTTPResponseStatus_extension_test),
            ("test_11_dynamic_coding_keys", test_11_dynamic_coding_keys),
            ("test_12_dynamic_coding_keys", test_12_dynamic_coding_keys),
            ("test_13_query_type", test_13_query_type),
            ("test_14_query", test_14_query),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(ElasticSwiftCoreTests.__allTests__ElasticSwiftCoreTests),
        ]
    }
#endif
