#if !canImport(ObjectiveC)
import XCTest

extension ElasticSwiftCodableUtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElasticSwiftCodableUtilsTests = [
        ("test_01_CodableValue_decode", test_01_CodableValue_decode),
        ("test_02_CodableValue_encode", test_02_CodableValue_encode),
        ("test_03_DecodableValue_decode", test_03_DecodableValue_decode),
        ("test_04_EncodableValue_encode", test_04_EncodableValue_encode),
        ("test_05_CodableValue_decode", test_05_CodableValue_decode),
        ("test_06_CodableValue_decode", test_06_CodableValue_decode),
        ("test_07_EncodableValue_encode", test_07_EncodableValue_encode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ElasticSwiftCodableUtilsTests.__allTests__ElasticSwiftCodableUtilsTests),
    ]
}
#endif
